/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('@construct-space/ui-web')['Button']
    ConstructLogo: typeof import('./src/components/ConstructLogo.vue')['default']
    Icon: typeof import('@construct-space/ui-web')['Icon']
    Input: typeof import('@construct-space/ui-web')['Input']
    InputPassword: typeof import('@construct-space/ui-web')['InputPassword']
    NotificationBell: typeof import('./src/components/NotificationBell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMenu: typeof import('@construct-space/ui-web')['SelectMenu']
    Switch: typeof import('@construct-space/ui-web')['Switch']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
  }
}
